
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @@author Vansh Cahawla
 */
public class JFrameViewAll extends javax.swing.JFrame {

    /**
     * Creates new form ViewAll
     */
    public JFrameViewAll() throws FileNotFoundException {
        initComponents();
        ItemArray iArr = new ItemArray(); // Creates a new ItemArray variable 
        int i = iArr.getCount(); // Stores the number of elements in the array
        DefaultTableModel model1 = (DefaultTableModel) ViewAllTable.getModel();  //creates the table model
        for (int j = 0; j < i; j++) { // loops through the array
            String code = iArr.getItemCode(j); // Extracts the itemCode of the Item
            String description = iArr.getDescription(j); // Extracts the description of the Item
            String unitsLeft = iArr.getUnitsLeft(j); // Extracts the numebr of units left of the Item
            String costPrice = iArr.getCostPrice(j); // Extracts the cost price of the item
            String SellingPrice = "" + iArr.getSellingPrice(j); // Extracts the selling price of the item
            String LastOrder = iArr.getDateLastOrder(j); // extracts the date of last order of the item
            model1.addRow(new Object[]{code, description, unitsLeft, costPrice, SellingPrice, LastOrder}); // inserts a row with the item's details
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewAllTable = new javax.swing.JTable();
        jButtonMainMenu = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewAllTable.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        ViewAllTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNum", "Description", "Units Left", "Cost Price", "Selling Price", "Date of Last Order"
            }
        ));
        jScrollPane1.setViewportView(ViewAllTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 820, 400));

        jButtonMainMenu.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonMainMenu.setText("Main Menu");
        jButtonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, -1, 40));

        jButtonHelp.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonHelp.setText("Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonMainMenuActionPerformed
        
    }//GEN-LAST:event_JButtonMainMenuActionPerformed

    private void JButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHelpActionPerformed

    }//GEN-LAST:event_JButtonHelpActionPerformed

    private void jButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainMenuActionPerformed
       this.hide(); // sets this frame to be invisible
        JFrameMainMenu j = new JFrameMainMenu(); // Creates a new Main Menu JFrame 
        j.show(); // Displays the Main Menu jFrame
    }//GEN-LAST:event_jButtonMainMenuActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
                if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("HELP.pdf"); //Looks for the Help file 
                Desktop.getDesktop().open(myFile); //Opens up the help pdf file

            } catch (IOException ex) {
            }

        }
    }//GEN-LAST:event_jButtonHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameViewAll().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFrameViewAll.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ViewAllTable;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
