
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.awt.Desktop;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vansh Chawla
 */
public class JFrameTill extends javax.swing.JFrame {
    double total; // a variable to store the total of the order
    ItemArray iArr; // an object of the type ItemArray
    DefaultTableModel Item;// the table
    public JFrameTill() throws FileNotFoundException {
        this.iArr = new ItemArray (); // initiates the iArr object
        initComponents();
        
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxItems = new javax.swing.JComboBox();
        jComboBoxUnits = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Paid = new javax.swing.JTextField();
        jButtonProceed = new javax.swing.JButton();
        jButtonAddItem = new javax.swing.JButton();
        jButtonNewOrder = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItems = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonBack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxItems.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jComboBoxItems.setToolTipText("");
        jComboBoxItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 150, 50));

        jComboBoxUnits.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jComboBoxUnits.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitsActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 120, 40));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Total:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 70, 30));

        Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidActionPerformed(evt);
            }
        });
        getContentPane().add(Paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 90, 40));

        jButtonProceed.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 140, 50));

        jButtonAddItem.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonAddItem.setText("Add To Cart");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 200, 40));

        jButtonNewOrder.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonNewOrder.setText("New Order");
        jButtonNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, 50));

        jButtonPrint.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 140, 50));

        jButton1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 140, 50));

        jButtonBack.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 140, 50));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 110, 30));

        jTextField1.setText("Customer ID");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, 30));

        jButton3.setText("GST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 130, 30));

        jTableItems.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jTableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price"
            }
        ));
        jScrollPane3.setViewportView(jTableItems);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 480));

        jButtonBack1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonBack1.setText("Back");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonProceedActionPerformed
        
    }//GEN-LAST:event_JButtonProceedActionPerformed

    private void jComboBoxItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxItemsActionPerformed

    private void PaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaidActionPerformed

    private void JButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNewOrderActionPerformed
       
            
        
    }//GEN-LAST:event_JButtonNewOrderActionPerformed

    private void JButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddItemActionPerformed

        
       
    }//GEN-LAST:event_JButtonAddItemActionPerformed

    private void JButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonBackActionPerformed
       
    }//GEN-LAST:event_JButtonBackActionPerformed

    private void JButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonPrintActionPerformed
     
    }//GEN-LAST:event_JButtonPrintActionPerformed

    private void JButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHelpActionPerformed
        
    }//GEN-LAST:event_JButtonHelpActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        double pay; 
        try {
        pay = Double.parseDouble(JOptionPane.showInputDialog ("Enter the amount the customer will pay")); // prompts the user to enter the amount they will pay
        if (pay < 0 ) { 
             pay = Double.parseDouble(JOptionPane.showInputDialog ("Enter a valid amount the customer will pay"));
        }
        }
        catch (NumberFormatException e) { 
               pay = Double.parseDouble(JOptionPane.showInputDialog ("Enter a valid amount the customer will pay")); 
                }
        String message = iArr.checkOut(total, pay);
        JOptionPane.showMessageDialog(null, message); //works out the change that the user will recieve
        JOptionPane.showMessageDialog(null, "This total includes GST"); //works out the change that the user will recieve including GST
    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
          GST();
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    public void GST()
    {
         try {
            
            ItemArray it = new ItemArray(); //an object of the type ItemArray
            double saleprice = 0; // A variable to store the selling price of the items
            String item = jComboBoxItems.getSelectedItem().toString(); // Gets the description of the item selected by the user from the combo box
            int amount = Integer.parseInt(jComboBoxUnits.getSelectedItem().toString()); // Gets the amount ordered by the user
            double price = it.itemprice(item, amount);//method to find out the items price using the items name,
            saleprice = amount * price;//calculating the amount of money required for the purchse
            it.updateFile(item, amount);//method to upadte the database,to the restoc list the amount of items bought using its name and the amount bought by the customber
            Item.addRow(new Object[]{item, amount, price*amount});//creating new row in the table using the items name and the amount of item with its price
            total = total + saleprice;//calculating final price
           double x;
           x= Double.parseDouble(jTextField2.getText());
            total = total+ (total *x);
            
            Paid.setText("R" + total);//displaying the total price
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameTill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButtonNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewOrderActionPerformed
         DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxItems.getModel(); // creates the combo box model
        Item = (DefaultTableModel) jTableItems.getModel(); // creates the table model
        total = 0; // sets the total to be null
        int size = 0; //The size of yhr index of the combo box
        model.removeAllElements();// clears the table
        Item.setRowCount (0); // resets the table for the new order
        Paid.setText(null);
        for (int i = 0; i < iArr.getCount(); i ++) { // loops through the array
            String name = iArr.getDescription(i); // Stores the description entered by the user
            model.insertElementAt(name, size);//inserting the item name at positon size
            size++;//moving to the next index of the combo box
        }
    }//GEN-LAST:event_jButtonNewOrderActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
         this.hide (); // sets this framme to be invisible
        JFrameLogIn j = new JFrameLogIn (); // creates a new Log In jFrame
        j.show();// Displays the log in jFrame
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
          try{ 
            MessageFormat header = new MessageFormat ("Page Header"); // Specifies the header of the page
            MessageFormat footer = new MessageFormat ("Page (1, number,integer)"); // specifies the footer of the page
            jTableItems.print (JTable.PrintMode.FIT_WIDTH, header, footer); //prints the table
            
        }
        catch (Exception e ){
            
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("HELP.pdf"); //Looks for the Help file 
                Desktop.getDesktop().open(myFile); //Opens up the help pdf file
 
            } catch (IOException ex) {
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                      
    try {
        String d= jTextField1.getText();
        String d1= "/Users/vanshchawla/Downloads/Gupta Tuck/";
        String d2 = d1.concat(d);
        String filePath = d2+"/tableexport.pdf";
        JTableToPDF(jTableItems, filePath);
        JOptionPane.showMessageDialog(null, "PDF exported successfully to: " + filePath);
    } catch (Exception ex) {
        Logger.getLogger(JFrameTill.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error exporting PDF");
    }
} 

private void JTableToPDF(JTable table, String filePath) throws Exception {
    Document document = new Document();
    PdfWriter.getInstance(document, new FileOutputStream(filePath));
    document.open();

    PdfPTable pdfTable = new PdfPTable(table.getColumnCount());

    // Add table header
    for (int i = 0; i < table.getColumnCount(); i++) {
        pdfTable.addCell(new Phrase(table.getColumnName(i)));
    }

    // Add table rows
    for (int i = 0; i < table.getRowCount(); i++) {
        for (int j = 0; j < table.getColumnCount(); j++) {
            pdfTable.addCell(new Phrase(table.getValueAt(i, j).toString()));
        }
    }

    document.add(pdfTable);
    document.close();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (Desktop.isDesktopSupported()) {
      
         //making a desktop object
         Desktop desktop = Desktop.getDesktop();
         try {
            URI uri = new URI("https://cbic-gst.gov.in/gst-goods-services-rates.html");
            desktop.browse(uri);
         } catch (IOException excp) {
            excp.printStackTrace();
         } catch (URISyntaxException excp) {
            excp.printStackTrace();
         }
      }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameTill().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFrameTill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Paid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonNewOrder;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JComboBox jComboBoxItems;
    private javax.swing.JComboBox jComboBoxUnits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableItems;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private Document newDocument() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
