
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vansh Cahawla
 */
public class JFrameMainMenu extends javax.swing.JFrame {

    public JFrameMainMenu() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonViewItem = new javax.swing.JButton();
        jButtonGeneralInformation = new javax.swing.JButton();
        jButtonViewAll = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonNewItem = new javax.swing.JButton();
        jButtonGoogleSearch = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonLogOut2 = new javax.swing.JButton();
        jButtonDeleteItem = new javax.swing.JButton();
        jButtonLogOut1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonViewItem.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonViewItem.setText("View Item");
        jButtonViewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewItemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 140, 40));

        jButtonGeneralInformation.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonGeneralInformation.setText("General Information");
        jButtonGeneralInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneralInformationActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGeneralInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, 40));

        jButtonViewAll.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonViewAll.setText("View All");
        jButtonViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 40));

        jButtonLogOut.setFont(new java.awt.Font("Britannic Bold", 1, 14)); // NOI18N
        jButtonLogOut.setText("Manager Dashboard");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 40));

        jButtonNewItem.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonNewItem.setText("New Item");
        jButtonNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewItemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        jButtonGoogleSearch.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonGoogleSearch.setText("Google Search");
        jButtonGoogleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoogleSearchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGoogleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 250, 80));

        jButtonHelp.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonHelp.setText("Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 40));

        jButtonLogOut2.setFont(new java.awt.Font("Britannic Bold", 1, 14)); // NOI18N
        jButtonLogOut2.setText("Add Manager ");
        jButtonLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOut2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 40));

        jButtonDeleteItem.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonDeleteItem.setText("Delete Item");
        jButtonDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteItemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 140, 40));

        jButtonLogOut1.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButtonLogOut1.setText("Log Out");
        jButtonLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOut1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 130, 40));

        jLabel10.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        jLabel10.setText("Main Menu");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sweets (1).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHelpActionPerformed
    
    }//GEN-LAST:event_JButtonHelpActionPerformed

    private void JButtonNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNewItemActionPerformed
        try {
             
            this.setVisible (false); // Sets this frame to be invisible
            JFrameNewItem p = new JFrameNewItem();// creates a new NewItem jFramme
            p.setVisible(true); // Displays the New Item JFrame
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JButtonNewItemActionPerformed

    private void JButtonViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonViewAllActionPerformed
        this.hide(); // Sets this frame to be invisible
        try {
            JFrameViewAll v = new JFrameViewAll(); // Creates a new View All JFrame
            v.setVisible(true); // Displays the View All JFrame
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JButtonViewAllActionPerformed

    private void JButtonViewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonViewItemActionPerformed
        
    }//GEN-LAST:event_JButtonViewItemActionPerformed

    private void JButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDeleteItemActionPerformed
       
    }//GEN-LAST:event_JButtonDeleteItemActionPerformed

    private void JButtonViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonViewUsersActionPerformed

    }//GEN-LAST:event_JButtonViewUsersActionPerformed

    private void JButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLogOutActionPerformed
        
    }//GEN-LAST:event_JButtonLogOutActionPerformed

    private void JButtonGoogleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonGoogleSearchActionPerformed
        
    }//GEN-LAST:event_JButtonGoogleSearchActionPerformed

    private void jButtonViewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewItemActionPerformed
        try {
            this.hide(); // Sets this frame to be invisible
            JFrameViewItem f = new JFrameViewItem(); // Creates a new ViewItems JFrame
            f.setVisible(true); // Displays the View Item JFrame
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewItemActionPerformed

    private void jButtonGeneralInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneralInformationActionPerformed
        try {
            this.hide();
            JFrameGenralInformation j = new JFrameGenralInformation (); 
            j.show ();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGeneralInformationActionPerformed

    private void jButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteItemActionPerformed
        try {
            this.setVisible(false); // Sets this frame to be invisible
            JFrameDeleteItem d = new JFrameDeleteItem();// Creates a new DeleteItem JFrame
            d.setVisible(true); // Displays the Delete Item JFrame
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonDeleteItemActionPerformed

    private void jButtonViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllActionPerformed
           try {
            this.hide(); // Sets this frame to be invisible
            JFrameViewAll f = new JFrameViewAll(); // Creates a new ViewItems JFrame
            f.setVisible(true); // Displays the View Item JFrame
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonViewAllActionPerformed

    private void jButtonNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewItemActionPerformed
        try {
            this.setVisible (false);
            JFrameNewItem j = new JFrameNewItem (); 
            j.setVisible (true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNewItemActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        this.setVisible(false); // Sets this frame to be invisible
        MMM l = new MMM();// Creates a new log in JFrame
        l.show(); // Displays the Log In JFrame
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("HELP.pdf"); //Looks for the Help file 
                Desktop.getDesktop().open(myFile); //Opens up the help pdf file

            } catch (IOException ex) {
            }

        }   
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jButtonGoogleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoogleSearchActionPerformed
       String url = "https://www.google.co.za/"; // A Variable to store the google URL
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(JFrameMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGoogleSearchActionPerformed

    private void jButtonLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOut1ActionPerformed
               this.setVisible (false); // Sets this frame to be invisible
            loginselec e = null;
            e = new loginselec(); // creates a new NewItem jFramme
            e.setVisible(true); // Displays the New Item JFramE
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogOut1ActionPerformed

    private void jButtonLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOut2ActionPerformed
        this.hide(); // Sets this frame to be invisible
        ManagerRegister h = new ManagerRegister(); 
        h.setVisible(true); // Displays the View Item JFrame
    }//GEN-LAST:event_jButtonLogOut2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameMainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteItem;
    private javax.swing.JButton jButtonGeneralInformation;
    private javax.swing.JButton jButtonGoogleSearch;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonLogOut1;
    private javax.swing.JButton jButtonLogOut2;
    private javax.swing.JButton jButtonNewItem;
    private javax.swing.JButton jButtonViewAll;
    private javax.swing.JButton jButtonViewItem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
