
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vansh Cahawla
 */
public class JFrameDeleteItem extends javax.swing.JFrame {

    ItemArray iArr = new ItemArray(); // a global object of the type ItemArray
    Item i = new Item(); // a global object of the type Item
    int itemNum; // global variable of the type int to store the item Number

    public JFrameDeleteItem() throws FileNotFoundException {
        initComponents();
        try {
        itemNum = Integer.parseInt(JOptionPane.showInputDialog("Enter the Item Number you want to delete")); // prompts the user to enter an item number to delete
        } 
         catch (NumberFormatException e) {
                itemNum = Integer.parseInt(JOptionPane.showInputDialog("Enter the correct itemNum"));
            } // The user is prompted to enter the itemNumber again
        while (iArr.SearchItemNumber(itemNum) == false) { // a while loop to search for the item entered by the user
            itemNum = Integer.parseInt(JOptionPane.showInputDialog("The Item number does not exist, please enter a valid item number")); // prompts the user to enter an item number to delete
            if (itemNum < 0) { // Validates the data to check if the user has entered a number less than 0
                itemNum = Integer.parseInt(JOptionPane.showInputDialog("Enter the valid Item Number you want to delete"));// prompts the user to enter the item number again as it was entered incorrectly the first time
            }
        }
        if (iArr.SearchItemNumber(itemNum)) { // searches for the itemNumber in the array
            i = iArr.SearchItem(itemNum); // Stores the item found into an item variable
            TextFieldItemNum.setText("" + i.getItemNumber()); // displays the itemnumber in the form 
            TextFieldItemDescription.setText(i.getDescription());  // diaplays the name of the item in the form
        } else {
            JOptionPane.showMessageDialog(null, "The item number is not found"); // If the item does not exist a mesage comes up

        }
    }
        
            
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldItemNum = new javax.swing.JTextField();
        TextFieldItemDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonHelp = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldItemNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldItemNumActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldItemNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 23, 140, 30));
        getContentPane().add(TextFieldItemDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 63, 140, 30));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Item Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 23, 162, 26));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel2.setText("Item Description");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 20));

        jButtonHelp.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonHelp.setText("Help");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 40));

        jButtonDelete.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, 40));

        jButtonCancel.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, 40));

        jLabel3.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldItemNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldItemNumActionPerformed

    }//GEN-LAST:event_TextFieldItemNumActionPerformed

    private void JButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDeleteItemActionPerformed
       
    }//GEN-LAST:event_JButtonDeleteItemActionPerformed

    private void JButtonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonMainMenuActionPerformed
        

    }//GEN-LAST:event_JButtonMainMenuActionPerformed

    private void JButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHelpActionPerformed
       if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("HELP.pdf"); //Looks for the Help file 
                Desktop.getDesktop().open(myFile); //Opens up the help pdf file

            } catch (IOException ex) {
            }

        }
    }//GEN-LAST:event_JButtonHelpActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         try {
            iArr.DeleteItem(itemNum); // A method from the ItemArray class to delete the item
        } catch (FileNotFoundException ex) { // catches the file not found exception
            Logger.getLogger(JFrameDeleteItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "The item has been deleted"); // shows a message saying that the item has been deleted
        this.hide(); // hides the jFrames
        JFrameMainMenu p = new JFrameMainMenu(); // creates a new JFrame
        p.show(); //displays the main menu

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.hide(); // hides the jFrames
        JFrameMainMenu p = new JFrameMainMenu(); // creates a new JFrame
        p.show(); //displays the main menu
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                File myFile = new File("HELP.pdf"); //Looks for the Help file 
                Desktop.getDesktop().open(myFile); //Opens up the help pdf file

            } catch (IOException ex) {
            }

        }
    }//GEN-LAST:event_jButtonHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDeleteItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameDeleteItem().setVisible(true); // sets the delete item jFrame to visable
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFrameDeleteItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldItemDescription;
    private javax.swing.JTextField TextFieldItemNum;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
