import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vansh Chawla
 */
public class tkinter extends javax.swing.JFrame {

    /**
     * Creates new form tkinter
     */
    public tkinter() {
        initComponents();
    }
public static void main(String[] args) {
        JFrame frame = new JFrame("Java Tkinter Launcher");
        JButton openTkinterButton = new JButton("Open Tkinter Script");

        openTkinterButton.addActionListener((ActionEvent e) -> {
            openTkinterWindow();
        });

        frame.getContentPane().add(openTkinterButton);
        frame.setSize(600, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }

    private static void openTkinterWindow() {
        try {
            // Specify the path to your Python script
            String pythonScriptPath = "/Users/vanshchawla/Downloads/otpmain/final.py";

            // Run the Python script using ProcessBuilder
            ProcessBuilder processBuilder = new ProcessBuilder("python3", pythonScriptPath);
            Process process = processBuilder.start();

            // Wait for the process to finish
            int exitCode = process.waitFor();

            // Print the exit code for debugging
            System.out.println("Python script exit code: " + exitCode);
        } catch (IOException | InterruptedException ex) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
